name: Auto Package

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  backend-package:
    name: Backend Package
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry
          cache-dependency-path: backend/poetry.lock

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4
          installer-parallel: true
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --only main --no-interaction --no-root

      - name: Build backend distribution
        run: poetry build --no-interaction

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist/*
          if-no-files-found: error

  frontend-package:
    name: Frontend Package
    runs-on: ubuntu-latest
    needs: backend-package
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Prepare frontend artifact
        run: |
          mkdir -p ../artifacts/frontend/.next
          cp package.json package-lock.json ../artifacts/frontend/
          cp -r public ../artifacts/frontend/
          cp -r .next/standalone ../artifacts/frontend/.next/
          cp -r .next/static ../artifacts/frontend/.next/
          if [ -f next.config.ts ]; then cp next.config.ts ../artifacts/frontend/; fi

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: artifacts/frontend
          if-no-files-found: error
